ticket.ticket_registration_type.*:
  type: config_entity
  label: 'Ticket registration type config'
  mapping:
    trid:
      type: string
      label: 'Ticket Registration ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    user_id:
      type: string
    langcode:
      type: string
    ticket_type:
      type: string
      label: 'Ticket Type'
    status:
      type: string
      label: 'Registration Status'
